version: '3.8'

services:
  php:
    build:
      context: docker/php
    container_name: symfony_ms_php
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      # jeśli używasz Xdebug, dodaj odpowiednie zmienne
      - COMPOSER_ALLOW_SUPERUSER=1

  nginx:
    image: nginx:stable
    container_name: symfony_ms_nginx
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:15
    container_name: symfony_ms_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfonypass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"

volumes:
  db_data:
